
import NavBar from '@/components/navBar'
import './globals.css'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { Provider } from 'react-redux'
import { store } from '../store/store'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <NavBar />
          {children}
          <ToastContainer limit={1} />
        </Provider>
      </body>
    </html>
  )
}
